name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-node@v2.4.0

      - name: Install Dependencies
        run: npm install

      - name: Build
        run: npm run build
